### PR TITLE
Update default

### PR DESCRIPTION
**Pull request by sahil-shubham**

### CODE REVIEW

**Comment by hargup** [comment]
@sahil-shubham lets remove the certbot lines and merge.

**Comment by sahil-shubham** [comment]
Removed the certbot lines and added config for slack plugin as that was missing. Also, would it be better to keep only the `sites-available/default` file in this repository, rather than making the whole nginx directory a repository?

**Comment by sahil-shubham** [comment]
Let's merge this whenever possible, I don't have the write access to this repository.

**Comment by hargup** [comment]
@sahil-shubham merged the PR, also gave write access to everyone in the team.

**Pull request merged**
